sudo: true
language: php

php:
  - 7.0
  - 7.1
  - 7.2

matrix:
  allow_failures:
    - php: 7.1
    - php: 7.2

before_install:
  - composer self-update

install:
  - composer install --no-interaction --prefer-source

script:
  - ./vendor/bin/tester -p php-cgi tests
#  - ./vendor/bin/tester -p $TESTER_PHP_BIN -c ./tests/GalekTests/Socials/php.ini -s ./tests/

after_failure:
  # Vytiskne obsah souborů *.actual
  - for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

after_script:
    - if [ "$TRAVIS_PHP_VERSION" == "7.0" ]; then
      wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
      && php coveralls.phar --verbose --config tests/.coveralls.yml
      || true;
      fi
