language: php

php:
  - 7.0
  - 7.1
  - 7.2

matrix:
  allow_failures:
    - php: 7.1
    - php: 7.2

before_install:
  - phpenv config-rm xdebug.ini || return 0
  - composer self-update

install:
  - travis_retry composer install --no-progress --prefer-dist

script:
  - vendor/bin/tester tests -s

after_failure:
  # Vytiskne obsah souborů *.actual
  - for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

jobs:
  include:
    - stage: "Code Coverage"
      script:
        - vendor/bin/tester -p phpdbg tests -s --coverage ./coverage.xml --coverage-src ./src
      after_script:
        - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
        - php coveralls.phar --verbose --config tests/.coveralls.yml

  allow_failures:
    - stage: "Code Coverage"

sudo: false

notifications:
  email: false